# Reinforcement Learning Example - FrozenLake 

In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state 
        rewards_current_episode += reward
        
        if done == True:
            break
    
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000

for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print('********** Q-Table *********')
print(q_table)

1000 :  0.03900000000000003
2000 :  0.20300000000000015
3000 :  0.4280000000000003
4000 :  0.5390000000000004
5000 :  0.6160000000000004
6000 :  0.6970000000000005
7000 :  0.6820000000000005
8000 :  0.6620000000000005
9000 :  0.7060000000000005
10000 :  0.6960000000000005
********** Q-Table *********
[[0.59722992 0.51033077 0.52429985 0.47672597]
 [0.33969243 0.29052697 0.35473078 0.52890547]
 [0.42217938 0.41591497 0.42731794 0.46157054]
 [0.31632212 0.22772496 0.28699441 0.43472034]
 [0.6239642  0.29589327 0.33110058 0.39973028]
 [0.         0.         0.         0.        ]
 [0.1421944  0.13817761 0.43898241 0.14240743]
 [0.         0.         0.         0.        ]
 [0.48900551 0.4590065  0.41516067 0.66489258]
 [0.5398354  0.70093633 0.48397428 0.41594204]
 [0.62450502 0.42707621 0.41615194 0.29232239]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.55769121 0.56004309 0.8276479  0.37871542]
 [0.72544035 0.94043275 0.73759099 0.734

In [6]:
for episode in range(3):
    state = env.reset()
    done = False
    print("Episode ", episode+1, "\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("You reached the goal!")
                time.sleep(3)
            else:
                print("You fell through a hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
You reached the goal!
